/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface FairChainEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allContractIds"
      | "getAllContractIds"
      | "productContracts"
      | "refund"
      | "registerContract"
      | "releaseAll"
      | "releaseMilestone"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ContractRegistered"
      | "EscrowRefunded"
      | "EscrowSettled"
      | "MilestoneReleased"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allContractIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllContractIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "productContracts",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "refund", values: [string]): string;
  encodeFunctionData(
    functionFragment: "registerContract",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "releaseAll", values: [string]): string;
  encodeFunctionData(
    functionFragment: "releaseMilestone",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "allContractIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllContractIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "productContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "releaseAll", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releaseMilestone",
    data: BytesLike
  ): Result;
}

export namespace ContractRegisteredEvent {
  export type InputTuple = [
    contractId: string,
    creator: AddressLike,
    ipfsCid: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    contractId: string,
    creator: string,
    ipfsCid: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    contractId: string;
    creator: string;
    ipfsCid: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowRefundedEvent {
  export type InputTuple = [contractId: string, timestamp: BigNumberish];
  export type OutputTuple = [contractId: string, timestamp: bigint];
  export interface OutputObject {
    contractId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowSettledEvent {
  export type InputTuple = [contractId: string, timestamp: BigNumberish];
  export type OutputTuple = [contractId: string, timestamp: bigint];
  export interface OutputObject {
    contractId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneReleasedEvent {
  export type InputTuple = [
    contractId: string,
    milestoneIndex: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    contractId: string,
    milestoneIndex: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    contractId: string;
    milestoneIndex: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FairChainEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): FairChainEscrow;
  waitForDeployment(): Promise<this>;

  interface: FairChainEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allContractIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getAllContractIds: TypedContractMethod<[], [string[]], "view">;

  productContracts: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint, boolean] & {
        contractId: string;
        ipfsCid: string;
        creator: string;
        createdAt: bigint;
        isCompleted: boolean;
      }
    ],
    "view"
  >;

  refund: TypedContractMethod<[_contractId: string], [void], "nonpayable">;

  registerContract: TypedContractMethod<
    [_contractId: string, _ipfsCid: string],
    [void],
    "nonpayable"
  >;

  releaseAll: TypedContractMethod<[_contractId: string], [void], "nonpayable">;

  releaseMilestone: TypedContractMethod<
    [_contractId: string, _milestoneIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allContractIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getAllContractIds"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "productContracts"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint, boolean] & {
        contractId: string;
        ipfsCid: string;
        creator: string;
        createdAt: bigint;
        isCompleted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[_contractId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerContract"
  ): TypedContractMethod<
    [_contractId: string, _ipfsCid: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "releaseAll"
  ): TypedContractMethod<[_contractId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "releaseMilestone"
  ): TypedContractMethod<
    [_contractId: string, _milestoneIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ContractRegistered"
  ): TypedContractEvent<
    ContractRegisteredEvent.InputTuple,
    ContractRegisteredEvent.OutputTuple,
    ContractRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "EscrowRefunded"
  ): TypedContractEvent<
    EscrowRefundedEvent.InputTuple,
    EscrowRefundedEvent.OutputTuple,
    EscrowRefundedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowSettled"
  ): TypedContractEvent<
    EscrowSettledEvent.InputTuple,
    EscrowSettledEvent.OutputTuple,
    EscrowSettledEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneReleased"
  ): TypedContractEvent<
    MilestoneReleasedEvent.InputTuple,
    MilestoneReleasedEvent.OutputTuple,
    MilestoneReleasedEvent.OutputObject
  >;

  filters: {
    "ContractRegistered(string,address,string,uint256)": TypedContractEvent<
      ContractRegisteredEvent.InputTuple,
      ContractRegisteredEvent.OutputTuple,
      ContractRegisteredEvent.OutputObject
    >;
    ContractRegistered: TypedContractEvent<
      ContractRegisteredEvent.InputTuple,
      ContractRegisteredEvent.OutputTuple,
      ContractRegisteredEvent.OutputObject
    >;

    "EscrowRefunded(string,uint256)": TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;
    EscrowRefunded: TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;

    "EscrowSettled(string,uint256)": TypedContractEvent<
      EscrowSettledEvent.InputTuple,
      EscrowSettledEvent.OutputTuple,
      EscrowSettledEvent.OutputObject
    >;
    EscrowSettled: TypedContractEvent<
      EscrowSettledEvent.InputTuple,
      EscrowSettledEvent.OutputTuple,
      EscrowSettledEvent.OutputObject
    >;

    "MilestoneReleased(string,uint256,uint256)": TypedContractEvent<
      MilestoneReleasedEvent.InputTuple,
      MilestoneReleasedEvent.OutputTuple,
      MilestoneReleasedEvent.OutputObject
    >;
    MilestoneReleased: TypedContractEvent<
      MilestoneReleasedEvent.InputTuple,
      MilestoneReleasedEvent.OutputTuple,
      MilestoneReleasedEvent.OutputObject
    >;
  };
}
