/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FairChainEscrow } from "./FairChainEscrow";
export * as factories from "./factories";
export { FairChainEscrow__factory } from "./factories/FairChainEscrow__factory";
